INSERT INTO tb_field_of_activity (name) VALUES
('Construção civil'),
('Obras viárias'),
('Obras ferroviárias'),
('Obras portuárias'),
('Obras aeroportuárias'),
('Barragens e hidrelétricas'),
('Rede de água'),
('Rede de esgoto'),
('Tratamento de água/esgoto'),
('Drenagem urbana'),
('Gestão de resíduos'),
('Recuperação ambiental'),
('Rede elétrica'),
('Subestações'),
('Energia renovável'),
('Iluminação pública'),
('Telecomunicações'),
('Terraplenagem'),
('Demolição'),
('Climatização'),
('Combate a incêndio'),
('Elevadores/escadas rolantes'),
('Segurança eletrônica'),
('Automação predial'),
('Pintura/revestimento'),
('Pisos/revestimentos cerâmicos'),
('Carpintaria/marcenaria'),
('Paisagismo'),
('Mobiliário urbano'),
('Ciclovias/passarelas'),
('Corredores de transporte público'),
('Sinalização viária'),
('Pavimentação/manutenção de vias'),
('Escolas/universidades'),
('Hospitais/postos de saúde'),
('Centros esportivos'),
('Bibliotecas/centros culturais'),
('Prédios administrativos')
ON CONFLICT DO NOTHING;
